export const CRYPTOPANIC_REST_CONNECTION_URL = 'CRYPTOPANIC_REST_CONNECTION_URL';
export const CRYPTOPANIC_REST_TIMER_UPDATE = 'CRYPTOPANIC_REST_TIMER_UPDATE';
export const CRYPTOPANIC_REST_API_KEY = 'CRYPTOPANIC_REST_API_KEY'
