export const NEWSDATA_REST_CONNECTION_URL = 'NEWSDATA_REST_CONNECTION_URL';
export const NEWSDATA_REST_TIMER_UPDATE = 'NEWSDATA_REST_TIMER_UPDATE'
export const NEWSDATA_REST_API_KEY = 'NEWSDATA_REST_API_KEY'
